# Generated by Django 6.0.3 on 2026-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='AI Generated Cover Letter'),
        ),
    ]
