# Generated by Django 6.0.3 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisreport_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='interview_questions',
            field=models.TextField(blank=True, help_text='AI Generated Interview Prep Questions'),
        ),
    ]
